# Copyright (c) 2026 Axonant
# SPDX-License-Identifier: MIT

"""meowcat public API — centralized ``__all__`` and lazy-load mapping.

This module exists so ``import meowcat`` only loads this tiny file + ``__init__.py``.
All actual modules are imported on first attribute access via :func:`__getattr__`.
"""

from __future__ import annotations

# -- Public API surface -------------------------------------------------------
# fmt: off
__all__ = [
    # Protocols
    "OrchestratorProtocol", "SettingsProtocol", "OrganProtocol", "CatProtocol", "KittenProtocol", "BrainStemProtocol",
    "HippocampusProtocol", "ThalamusProtocol", "LLMBrainProtocol",
    "AdapterProtocol",
    "AmygdalaProtocol", "FrontalCortexProtocol", "HypothalamusProtocol",
    "CortexProtocol", "EarsProtocol", "EyesProtocol", "WhiskersProtocol",
    "MouthProtocol", "PurrProtocol", "TailProtocol",
    "AnomalyGrowthProtocol", "CorrectionGrowthProtocol",
    "CrystallizerProtocol", "RoleEmergenceProtocol",
    "SecurityPolicyProtocol",
    "PawsProtocol", "GraphStorageProtocol", "L6StorageProtocol",
    "VectorStorageProtocol", "SharedStorageProtocol", "StageProtocol",
    "LLMProviderProtocol", "Diagnosable",
    # Models
    "EntityShape", "ConnectionShape", "EpisodeShape", "FocusShape",
    "SubTaskShape", "TaskResultShape", "OrchestratorReportShape",
    "CandidateShape", "LocateResultShape", "MaintenanceReportShape",
    "StageEvent", "PipelineContext", "LoopEvent",
    "MergeProposalShape", "KittenCapability", "WorkflowShape", "LLMConfig", "ModelConfig",
    # Errors
    "MeowCatError", "OrganNotMountedError", "LoopFailedError",
    "StageTimeoutError",
    "IllegalNeuralPathError", "ReflexPathInvalidError",
    "NoReflexMatchedError", "OrganProtocolMismatchError", "StandaloneCatError",
    "CircuitOpenError",
    "OrganDelegateError",
    # Skeleton
    "CatBase", "CatHook", "Colony", "ColonyConfig", "ColonyOwner", "ColonyRules", "EventBus", "Pipeline",
    # v0.5.9 Subsystems
    "OrganHost", "Nervous", "ReflexArc", "assemble_default_cat",
    # v0.5.20 Shared mount
    "mount_known_organs",
    # Loop event names
    "LocateEvent", "RememberEvent", "OrchestrateEvent", "GrowthEvent",
    "Lifecycle", "KittenEvent", "NerveEvent", "SelfEvent", "FusionEvent", "ALL_EVENTS",
    # v0.5.1 Nervous system
    "Wiring", "WiringSnapshot", "Organ", "Edge",
    "Reflex", "ReflexArc", "ReflexRegistry", "Trigger",
    "BUILTIN_REFLEX_PATHS",
    "PerceptionContext", "Modality", "infer_modality",
    "anatomy", "biology", "OrganSpec",
    "ANOMALY_GROWTH", "CORRECTION_GROWTH",
    "CRYSTALLIZER", "ROLE_EMERGENCE",
    "organ_roles", "ORGAN_ROLES",
    # v0.5.11 Organ base class
    "OrganMixin",
    # v0.5.22 New primitives
    "Stethoscope", "Needle", "NeedleDisabledError",
    # v1.0.3 Wiring visualization
    "render_wiring",
    # v0.5.27 Atomic paths
    "Path", "PathRegistry", "BUILTIN_PATHS", "register_builtin_paths",
    # v0.5.28a Chains
    "Chain", "ChainRegistry", "BUILTIN_CHAINS", "register_builtin_chains",
    "MEMORY_SEARCH_CHAIN", "FULL_REASONING_CHAIN",
    "TOOL_EXEC_CHAIN", "MAINTENANCE_CHAIN", "DIAGNOSTIC_CHAIN",
    "WORKFLOW_CHAIN",
    # v0.5.28b Loops
    "Loop", "LoopRegistry", "BUILTIN_LOOPS", "register_default_loops",
    "CONVERSATION_LOOP", "TOOL_EXECUTION_LOOP",
    "DANGER_RESPONSE_LOOP", "MAINTENANCE_LOOP", "DIAGNOSTIC_LOOP",
    # v1.0.4 Loop sequences
    "LoopSequence", "LoopSequenceRegistry", "DAILY_MAINTENANCE_SEQ",
    # v0.5.23 Tools system
    "Tool", "ToolSpec", "RiskLevel", "ToolRegistry",
    "Skill", "SkillSpec", "SkillRegistry",
    "BUILTIN_TOOLS", "PawsEngine",
    # Builtin defaults
    "create_cat",
    "NoopAmygdala", "NoopBrainstem", "NoopFrontal", "NoopHypothalamus", "NoopCortex",
    "NoopCerebrum", "NoopCerebellum",
    "NoopEars", "NoopEyes", "NoopWhiskers",
    "NoopMouth", "NoopPaws", "NoopPurr", "NoopTail",
    "NoopThalamus", "NoopHippocampus",
    # v1.0.16 Growth organs
    "NoopAnomalyGrowth", "NoopCorrectionGrowth", "NoopCrystallizer", "NoopRoleEmergence",
    # v1.0.17 Pipeline Stages
    "BaseStage",
    "NoopIngestStage", "NoopLocateStage", "NoopRouteStage",
    "NoopExecuteStage", "NoopPostStage", "NoopCompressStage",
    "build_default_pipeline",
    "InMemoryGraphStore", "InMemoryL6Store",
    "InMemoryVectorStore", "InMemorySharedStore",
    # v1.0.7 Pluggable
    "Pluggable",
    # v1.0.12 Colony federation
    "FederationTransport", "TCPSocketTransport", "RedisPubSubTransport",
    # v1.0.10 Gateway
    "Gateway", "SignalContext",
    "IoAdapterProtocol", "GatewayProtocol",
    "HttpAdapter", "WsAdapter", "WebhookAdapter", "CliAdapter", "IpcAdapter",
    # v1.0.13 Signal Middleware
    "SignalCall", "SignalMiddleware",
    "SignalLogger", "RateLimiter", "TimeoutGuard", "ContextInjector",
    "CircuitState",
    # v1.1.9 I18n
    "I18n",
    # v1.1.10 CommandRouter
    "Command", "CommandContext", "CommandRouter",
    # v1.1.11 System commands
    "register_system_commands", "is_debug",
    # v1.1.12 Colony commands
    "register_colony_commands",
    # v1.1.13 Textual TUI
    "MeowTui",
    # v1.1.14 MCP Client
    "MCPClient", "MCPServerConfig", "MCPTool",
    # v1.1.15 SKILL.md Loader
    "SkillLoader",
    # v1.1.16 General Tools
    "BrowserTool", "ChromaStore", "get_shared_client", "close_shared_client",
    # v1.1.17 Crystallizer
    "Crystallizer", "DefaultDetector",
    # v1.1.18 SharedStore + Log
    "SharedStore", "MeowLog",
    # v1.1.19 Persistent Storage
    "SqliteGraphStore", "JsonlL6Store", "JsonlEpisodeStore",
    # v1.1.20 Vector Store + Shared Memory
    "VectorStore", "SharedMemoryPool",
    # v1.1.22 Collective Growth + Emergence
    "CollectiveGrowth", "CollectiveEmergence",
    # v1.1.23 ScribblePad
    "ScribblePad", "DefaultScribbleFilter", "DefaultScribbleLogger",
    "DefaultScribblePersister",
    # v1.1.24 PinealGland + FusionCycle
    "PinealGland", "Insight",
    "DefaultMerger", "DefaultContradiction", "DefaultInsightFilter",
    "FusionCycle",
    # v1.1.25 Cortex worldview L1
    "Cortex", "DefaultRuleExtractor",
    # v1.1.26 active growth
    "BlindSpotDetector", "ToolFailureLearner", "HotPathObserver",
    "ActiveGrowthPack",
    # v1.1.27 metacognition L3
    "Metacognition",
    # v1.2.0 CatSelf + default closed loops
    "CatSelf", "SelfSnapshot",
    "DefaultConversationLoop", "DefaultTaskLoop", "DefaultLearnLoop",
    # v1.1.28 GlobalColonyRegistry
    "GlobalColonyRegistry",
    # v1.1.29 skeleton abstraction
    "AsyncApprovalGate", "ApprovalRequest", "ApprovalStatus",
    "KeywordToolMatcher",
    "Theme",
    "BaseWorker", "CheckpointStore", "InMemoryCheckpointStore",
    "WorkerState", "WorkerStatus", "WorkerScheduler",
    # v1.2.9 Renovated organs
    "RENOVATED_ORGAN_MAP",
    "RenovatedAmygdala", "RenovatedBrainstem", "RenovatedFrontal",
    "RenovatedHypothalamus", "RenovatedCortex",
    "RenovatedCerebrum", "RenovatedCerebellum",
    "RenovatedEars", "RenovatedEyes", "RenovatedMouth", "RenovatedPaws",
    "RenovatedPurr", "RenovatedTail", "RenovatedWhiskers",
    "RenovatedThalamus", "RenovatedHippocampus",
    "RenovatedAnomalyGrowth", "RenovatedCorrectionGrowth",
    "RenovatedCrystallizer", "RenovatedRoleEmergence",
    # v1.2.8 Presets
    "KeywordPreset", "PromptPreset", "OrganPrompt",
    "KW_EN", "KW_ZH", "KW_BILINGUAL",
    "PROMPT_DEFAULT", "PROMPT_ZH",
    "KW_PRESETS", "PROMPT_PRESETS",
    "ImplementationStyle",
    "_UNSET",
    # v1.2.14 Organ adapters
    "AgentOrgan", "SkillOrgan",
    "CerebrumAgent", "CerebellumAgent", "ThalamusAgent",
    "HippocampusAgent", "AmygdalaAgent", "BrainstemAgent",
    "FrontalAgent", "HypothalamusAgent", "CortexAgent",
    "EarsAgent", "EyesAgent", "WhiskersAgent", "PawsAgent",
    "MouthAgent", "PurrAgent", "TailAgent",
    # v1.2.18 Event payload types
    "LifecycleStartPayload", "LifecycleShutdownPayload",
    "PerceiveStartPayload", "PerceiveEndPayload",
    "NerveSignalPayload",
    "LocatePrePayload", "LocatePostPayload", "RouteDecidedPayload",
    "RememberPrePayload", "RememberPostPayload",
    "CompressPrePayload", "CompressPostPayload",
    "OrchestrateStartPayload", "OrchestrateEndPayload",
    "GrowthAnomalyPayload", "GrowthCorrectionPayload",
    "CrystallizePayload", "RoleEmergePayload",
    "KittenSpawnedPayload", "KittenExecutingPayload", "KittenCompletedPayload",
    "KittenStuckPayload", "KittenDismissedPayload", "KittenMergeAbsorbedPayload",
    "SelfSnapshotPayload", "SelfReflectPayload",
    "FusionSelfPayload", "FusionColonyPayload",
    "FusionTriggerStartPayload", "FusionTriggerEndPayload",
    "EVENT_PAYLOAD_MAP",
    # v1.2.21 Telemetry
    "SignalSpan", "Tracer", "Metrics",
    "TelemetryEvent", "TelemetrySpanPayload",
    # v1.3.6 Model shelf
    "ProviderEntry", "BUILTIN_PROVIDERS", "ModelShelf", "FallbackChain",
    # v1.3.6 Compression manager
    "CompressionManager", "CompressionConfig",
    # v1.3.6 Remember policy
    "RememberPolicy", "RememberConfig",
    # v1.3.6 Clarify manager
    "ClarifyManager", "ClarifyConfig", "ClarifyResult",
    # v1.3.6 Budget tracker
    "BudgetTracker", "BudgetConfig",
    # v1.3.6 Noise filter
    "NoiseFilter", "NoiseFilterConfig",
    # v1.3.6 Topic closure detector
    "TopicClosureDetector", "TopicClosureConfig", "TopicClosureResult",
    # v1.3.6 Checkpoint store
    "CheckpointConfig", "JsonCheckpointStore",
    # v1.3.6 Focus store
    "FocusStore", "JsonFocusStore", "FocusState",
    # v1.3.6 Plan reviser
    "PlanReviser", "PlanReviserConfig", "RevisionStrategy", "RevisionContext", "RevisionResult",
    # v1.3.6 Task orchestrator
    "TaskOrchestrator", "TaskNode", "TaskStatus", "TaskResult", "TaskExecutor",
]
# fmt: on


# -- Lazy import map: name → (module_path, attribute) ------------------------
# First access to any name triggers importlib.import_module + getattr,
# then caches result in meowcat.__dict__ so __getattr__ is only called once.
_LAZY_MAP: dict[str, tuple[str, str]] = {
    # — protocols —
    "OrchestratorProtocol":    ("meowcat.protocols", "OrchestratorProtocol"),
    "SettingsProtocol":        ("meowcat.protocols", "SettingsProtocol"),
    "OrganProtocol":           ("meowcat.protocols", "OrganProtocol"),
    "CatProtocol":             ("meowcat.protocols", "CatProtocol"),
    "KittenProtocol":          ("meowcat.protocols", "KittenProtocol"),
    "BrainStemProtocol":       ("meowcat.protocols", "BrainStemProtocol"),
    "HippocampusProtocol":     ("meowcat.protocols", "HippocampusProtocol"),
    "ThalamusProtocol":        ("meowcat.protocols", "ThalamusProtocol"),
    "LLMBrainProtocol":        ("meowcat.protocols", "LLMBrainProtocol"),
    "AdapterProtocol":         ("meowcat.protocols", "AdapterProtocol"),
    "AmygdalaProtocol":        ("meowcat.protocols", "AmygdalaProtocol"),
    "FrontalCortexProtocol":   ("meowcat.protocols", "FrontalCortexProtocol"),
    "HypothalamusProtocol":    ("meowcat.protocols", "HypothalamusProtocol"),
    "CortexProtocol":          ("meowcat.protocols", "CortexProtocol"),
    "EarsProtocol":            ("meowcat.protocols", "EarsProtocol"),
    "EyesProtocol":            ("meowcat.protocols", "EyesProtocol"),
    "WhiskersProtocol":        ("meowcat.protocols", "WhiskersProtocol"),
    "MouthProtocol":           ("meowcat.protocols", "MouthProtocol"),
    "PurrProtocol":            ("meowcat.protocols", "PurrProtocol"),
    "TailProtocol":            ("meowcat.protocols", "TailProtocol"),
    "AnomalyGrowthProtocol":   ("meowcat.protocols", "AnomalyGrowthProtocol"),
    "CorrectionGrowthProtocol": ("meowcat.protocols", "CorrectionGrowthProtocol"),
    "CrystallizerProtocol":    ("meowcat.protocols", "CrystallizerProtocol"),
    "RoleEmergenceProtocol":   ("meowcat.protocols", "RoleEmergenceProtocol"),
    "SecurityPolicyProtocol":  ("meowcat.protocols", "SecurityPolicyProtocol"),
    "PawsProtocol":            ("meowcat.protocols", "PawsProtocol"),
    "GraphStorageProtocol":    ("meowcat.protocols", "GraphStorageProtocol"),
    "L6StorageProtocol":       ("meowcat.protocols", "L6StorageProtocol"),
    "VectorStorageProtocol":   ("meowcat.protocols", "VectorStorageProtocol"),
    "SharedStorageProtocol":   ("meowcat.protocols", "SharedStorageProtocol"),
    "StageProtocol":           ("meowcat.protocols", "StageProtocol"),
    "LLMProviderProtocol":     ("meowcat.protocols", "LLMProviderProtocol"),
    "Diagnosable":             ("meowcat.protocols", "Diagnosable"),
    "FederationTransport":     ("meowcat.protocols", "FederationTransport"),
    # — models —
    "EntityShape":             ("meowcat.models", "EntityShape"),
    "ConnectionShape":         ("meowcat.models", "ConnectionShape"),
    "EpisodeShape":            ("meowcat.models", "EpisodeShape"),
    "FocusShape":              ("meowcat.models", "FocusShape"),
    "SubTaskShape":            ("meowcat.models", "SubTaskShape"),
    "TaskResultShape":         ("meowcat.models", "TaskResultShape"),
    "OrchestratorReportShape": ("meowcat.models", "OrchestratorReportShape"),
    "CandidateShape":          ("meowcat.models", "CandidateShape"),
    "LocateResultShape":       ("meowcat.models", "LocateResultShape"),
    "MaintenanceReportShape":  ("meowcat.models", "MaintenanceReportShape"),
    "StageEvent":              ("meowcat.models", "StageEvent"),
    "PipelineContext":         ("meowcat.models", "PipelineContext"),
    "LoopEvent":               ("meowcat.models", "LoopEvent"),
    "MergeProposalShape":      ("meowcat.models", "MergeProposalShape"),
    "KittenCapability":        ("meowcat.models", "KittenCapability"),
    "WorkflowShape":           ("meowcat.models", "WorkflowShape"),
    "LLMConfig":               ("meowcat.models", "LLMConfig"),
    "ModelConfig":             ("meowcat.models", "ModelConfig"),
    # — errors —
    "MeowCatError":              ("meowcat.errors", "MeowCatError"),
    "OrganNotMountedError":      ("meowcat.errors", "OrganNotMountedError"),
    "LoopFailedError":           ("meowcat.errors", "LoopFailedError"),
    "StageTimeoutError":         ("meowcat.errors", "StageTimeoutError"),
    "IllegalNeuralPathError":    ("meowcat.errors", "IllegalNeuralPathError"),
    "ReflexPathInvalidError":    ("meowcat.errors", "ReflexPathInvalidError"),
    "NoReflexMatchedError":      ("meowcat.errors", "NoReflexMatchedError"),
    "OrganProtocolMismatchError": ("meowcat.errors", "OrganProtocolMismatchError"),
    "StandaloneCatError":        ("meowcat.errors", "StandaloneCatError"),
    "CircuitOpenError":          ("meowcat.errors", "CircuitOpenError"),
    "OrganDelegateError":       ("meowcat.errors", "OrganDelegateError"),
    # — skeleton / assembly —
    "CatBase":                ("meowcat.assembly", "CatBase"),
    "CatHook":                ("meowcat.assembly", "CatHook"),
    "assemble_default_cat":   ("meowcat.assembly", "assemble_default_cat"),
    "mount_known_organs":     ("meowcat.assembly", "mount_known_organs"),
    # — colony —
    "Colony":               ("meowcat.colony", "Colony"),
    "ColonyConfig":         ("meowcat.colony", "ColonyConfig"),
    "ColonyOwner":          ("meowcat.colony", "ColonyOwner"),
    "ColonyRules":          ("meowcat.colony", "ColonyRules"),
    "GlobalColonyRegistry": ("meowcat.colony", "GlobalColonyRegistry"),
    "SharedMemoryPool":     ("meowcat.colony.memory", "SharedMemoryPool"),
    # — colony transports —
    "TCPSocketTransport":   ("meowcat.colony.transports", "TCPSocketTransport"),
    "RedisPubSubTransport": ("meowcat.colony.transports", "RedisPubSubTransport"),
    # — events —
    "EventBus":          ("meowcat.events", "EventBus"),
    "ALL_EVENTS":        ("meowcat.events", "ALL_EVENTS"),
    "FusionEvent":       ("meowcat.events", "FusionEvent"),
    "GrowthEvent":       ("meowcat.events", "GrowthEvent"),
    "KittenEvent":       ("meowcat.events", "KittenEvent"),
    "Lifecycle":         ("meowcat.events", "Lifecycle"),
    "LocateEvent":       ("meowcat.events", "LocateEvent"),
    "NerveEvent":        ("meowcat.events", "NerveEvent"),
    "OrchestrateEvent":  ("meowcat.events", "OrchestrateEvent"),
    "RememberEvent":     ("meowcat.events", "RememberEvent"),
    "SelfEvent":         ("meowcat.events", "SelfEvent"),
    # — wiring / nervous / reflex / host —
    "OrganHost":            ("meowcat.host", "OrganHost"),
    "Nervous":              ("meowcat.nervous", "Nervous"),
    "SignalCall":           ("meowcat.nervous", "SignalCall"),
    "SignalMiddleware":     ("meowcat.nervous", "SignalMiddleware"),
    "CircuitState":         ("meowcat.nervous", "CircuitState"),
    "Wiring":               ("meowcat.wiring", "Wiring"),
    "WiringSnapshot":       ("meowcat.wiring", "WiringSnapshot"),
    "Organ":                ("meowcat.wiring", "Organ"),
    "Edge":                 ("meowcat.wiring", "Edge"),
    "ReflexArc":            ("meowcat.reflex", "ReflexArc"),
    "Reflex":               ("meowcat.reflex", "Reflex"),
    "ReflexRegistry":       ("meowcat.reflex", "ReflexRegistry"),
    "Trigger":              ("meowcat.reflex", "Trigger"),
    "BUILTIN_REFLEX_PATHS": ("meowcat.reflex", "BUILTIN_REFLEX_PATHS"),
    # — middleware —
    "SignalLogger":    ("meowcat.middleware", "SignalLogger"),
    "RateLimiter":     ("meowcat.middleware", "RateLimiter"),
    "TimeoutGuard":    ("meowcat.middleware", "TimeoutGuard"),
    "ContextInjector": ("meowcat.middleware", "ContextInjector"),
    # — pluggable / organ_base —
    "Pluggable":  ("meowcat.pluggable", "Pluggable"),
    "OrganMixin": ("meowcat.organ_base", "OrganMixin"),
    # — pipeline —
    "Pipeline": ("meowcat.pipeline", "Pipeline"),
    # — perception —
    "PerceptionContext": ("meowcat.perception", "PerceptionContext"),
    "Modality":          ("meowcat.perception", "Modality"),
    "infer_modality":    ("meowcat.perception", "infer_modality"),
    # — diagnosis / injection —
    "Stethoscope":       ("meowcat.diagnose", "Stethoscope"),
    "render_wiring":     ("meowcat.diagnose", "render_wiring"),
    "Needle":            ("meowcat.inject", "Needle"),
    "NeedleDisabledError": ("meowcat.inject", "NeedleDisabledError"),
    # — path / chain / loops —
    "Path":                   ("meowcat.path", "Path"),
    "PathRegistry":           ("meowcat.path", "PathRegistry"),
    "BUILTIN_PATHS":          ("meowcat.path", "BUILTIN_PATHS"),
    "register_builtin_paths": ("meowcat.path", "register_builtin_paths"),
    "Chain":                  ("meowcat.chain", "Chain"),
    "ChainRegistry":          ("meowcat.chain", "ChainRegistry"),
    "BUILTIN_CHAINS":         ("meowcat.chain", "BUILTIN_CHAINS"),
    "register_builtin_chains": ("meowcat.chain", "register_builtin_chains"),
    "MEMORY_SEARCH_CHAIN":    ("meowcat.chain", "MEMORY_SEARCH_CHAIN"),
    "FULL_REASONING_CHAIN":   ("meowcat.chain", "FULL_REASONING_CHAIN"),
    "TOOL_EXEC_CHAIN":        ("meowcat.chain", "TOOL_EXEC_CHAIN"),
    "MAINTENANCE_CHAIN":      ("meowcat.chain", "MAINTENANCE_CHAIN"),
    "DIAGNOSTIC_CHAIN":       ("meowcat.chain", "DIAGNOSTIC_CHAIN"),
    "WORKFLOW_CHAIN":         ("meowcat.chain", "WORKFLOW_CHAIN"),
    "Loop":                   ("meowcat.loops", "Loop"),
    "LoopRegistry":           ("meowcat.loops", "LoopRegistry"),
    "BUILTIN_LOOPS":          ("meowcat.loops", "BUILTIN_LOOPS"),
    "register_default_loops": ("meowcat.loops", "register_default_loops"),
    "CONVERSATION_LOOP":      ("meowcat.loops", "CONVERSATION_LOOP"),
    "TOOL_EXECUTION_LOOP":    ("meowcat.loops", "TOOL_EXECUTION_LOOP"),
    "DANGER_RESPONSE_LOOP":   ("meowcat.loops", "DANGER_RESPONSE_LOOP"),
    "MAINTENANCE_LOOP":       ("meowcat.loops", "MAINTENANCE_LOOP"),
    "DIAGNOSTIC_LOOP":        ("meowcat.loops", "DIAGNOSTIC_LOOP"),
    "LoopSequence":           ("meowcat.loops", "LoopSequence"),
    "LoopSequenceRegistry":   ("meowcat.loops", "LoopSequenceRegistry"),
    "DAILY_MAINTENANCE_SEQ":  ("meowcat.loops", "DAILY_MAINTENANCE_SEQ"),
    # — tools (pure abstractions) —
    "Tool":               ("meowcat.tools", "Tool"),
    "ToolSpec":           ("meowcat.tools", "ToolSpec"),
    "ToolRegistry":       ("meowcat.tools", "ToolRegistry"),
    "RiskLevel":          ("meowcat.tools", "RiskLevel"),
    "Skill":              ("meowcat.tools", "Skill"),
    "SkillSpec":          ("meowcat.tools", "SkillSpec"),
    "SkillRegistry":      ("meowcat.tools", "SkillRegistry"),
    "PawsEngine":         ("meowcat.tools", "PawsEngine"),
    "KeywordToolMatcher": ("meowcat.tools", "KeywordToolMatcher"),
    # — plus (concrete implementations) —
    "BrowserTool":     ("meowcat.plus", "BrowserTool"),
    "ChromaStore":     ("meowcat.plus", "ChromaStore"),
    "MCPClient":       ("meowcat.plus", "MCPClient"),
    "MCPServerConfig": ("meowcat.plus", "MCPServerConfig"),
    "MCPTool":         ("meowcat.plus", "MCPTool"),
    "SkillLoader":     ("meowcat.plus", "SkillLoader"),
    "Crystallizer":    ("meowcat.plus", "Crystallizer"),
    "DefaultDetector": ("meowcat.plus", "DefaultDetector"),
    "BUILTIN_TOOLS":   ("meowcat.plus.tools", "BUILTIN_TOOLS"),
    # — storage —
    "SharedStore":      ("meowcat.storage", "SharedStore"),
    "SqliteGraphStore": ("meowcat.storage", "SqliteGraphStore"),
    "JsonlL6Store":     ("meowcat.storage", "JsonlL6Store"),
    "JsonlEpisodeStore": ("meowcat.storage", "JsonlEpisodeStore"),
    "VectorStore":      ("meowcat.storage", "VectorStore"),
    # — biology —
    "CollectiveGrowth":    ("meowcat.biology", "CollectiveGrowth"),
    "CollectiveEmergence": ("meowcat.biology", "CollectiveEmergence"),
    "OrganSpec":           ("meowcat.biology", "OrganSpec"),
    "ANOMALY_GROWTH":      ("meowcat.biology", "ANOMALY_GROWTH"),
    "CORRECTION_GROWTH":   ("meowcat.biology", "CORRECTION_GROWTH"),
    "CRYSTALLIZER":        ("meowcat.biology", "CRYSTALLIZER"),
    "ROLE_EMERGENCE":      ("meowcat.biology", "ROLE_EMERGENCE"),
    "ScribblePad":             ("meowcat.biology.scribble_pad", "ScribblePad"),
    "DefaultScribbleFilter":   ("meowcat.biology.scribble_pad", "DefaultScribbleFilter"),
    "DefaultScribbleLogger":   ("meowcat.biology.scribble_pad", "DefaultScribbleLogger"),
    "DefaultScribblePersister": ("meowcat.biology.scribble_pad", "DefaultScribblePersister"),
    "PinealGland":          ("meowcat.biology.pineal_gland", "PinealGland"),
    "Insight":              ("meowcat.biology.pineal_gland", "Insight"),
    "DefaultMerger":        ("meowcat.biology.pineal_gland", "DefaultMerger"),
    "DefaultContradiction": ("meowcat.biology.pineal_gland", "DefaultContradiction"),
    "DefaultInsightFilter": ("meowcat.biology.pineal_gland", "DefaultInsightFilter"),
    "FusionCycle":          ("meowcat.biology.fusion_cycle", "FusionCycle"),
    "Cortex":               ("meowcat.biology.cortex", "Cortex"),
    "DefaultRuleExtractor": ("meowcat.biology.cortex", "DefaultRuleExtractor"),
    "BlindSpotDetector":    ("meowcat.biology.active_growth", "BlindSpotDetector"),
    "ToolFailureLearner":   ("meowcat.biology.active_growth", "ToolFailureLearner"),
    "HotPathObserver":      ("meowcat.biology.active_growth", "HotPathObserver"),
    "ActiveGrowthPack":     ("meowcat.biology.active_growth_pack", "ActiveGrowthPack"),
    "Metacognition":        ("meowcat.biology.metacognition", "Metacognition"),
    "CatSelf":              ("meowcat.biology.cat_self", "CatSelf"),
    "SelfSnapshot":         ("meowcat.biology.cat_self", "SelfSnapshot"),
    "DefaultConversationLoop": ("meowcat.biology.cat_self", "DefaultConversationLoop"),
    "DefaultTaskLoop":      ("meowcat.biology.cat_self", "DefaultTaskLoop"),
    "DefaultLearnLoop":     ("meowcat.biology.cat_self", "DefaultLearnLoop"),
    # — log —
    "MeowLog":              ("meowcat.log", "MeowLog"),
    # — coordination —
    "AsyncApprovalGate":    ("meowcat.coordination", "AsyncApprovalGate"),
    "ApprovalRequest":      ("meowcat.coordination", "ApprovalRequest"),
    "ApprovalStatus":       ("meowcat.coordination", "ApprovalStatus"),
    # — worker —
    "BaseWorker":             ("meowcat.worker", "BaseWorker"),
    "CheckpointStore":        ("meowcat.worker", "CheckpointStore"),
    "InMemoryCheckpointStore": ("meowcat.worker", "InMemoryCheckpointStore"),
    "WorkerState":            ("meowcat.worker", "WorkerState"),
    "WorkerStatus":           ("meowcat.worker", "WorkerStatus"),
    "WorkerScheduler":        ("meowcat.worker.scheduler", "WorkerScheduler"),
    # — utils —
    "get_shared_client":   ("meowcat.utils", "get_shared_client"),
    "close_shared_client": ("meowcat.utils", "close_shared_client"),
    # — gateway —
    "Gateway":           ("meowcat.gateway", "Gateway"),
    "SignalContext":     ("meowcat.gateway.protocol", "SignalContext"),
    "IoAdapterProtocol": ("meowcat.gateway.protocol", "IoAdapterProtocol"),
    "GatewayProtocol":   ("meowcat.gateway.protocol", "GatewayProtocol"),
    "HttpAdapter":       ("meowcat.plus.gateway", "HttpAdapter"),
    "WsAdapter":         ("meowcat.plus.gateway", "WsAdapter"),
    "WebhookAdapter":    ("meowcat.plus.gateway", "WebhookAdapter"),
    "CliAdapter":        ("meowcat.plus.gateway", "CliAdapter"),
    "IpcAdapter":        ("meowcat.plus.gateway", "IpcAdapter"),
    # — cli —
    "Command":                ("meowcat.cli", "Command"),
    "CommandContext":         ("meowcat.cli", "CommandContext"),
    "CommandRouter":          ("meowcat.cli", "CommandRouter"),
    "I18n":                   ("meowcat.cli", "I18n"),
    "Theme":                  ("meowcat.cli", "Theme"),
    "register_system_commands": ("meowcat.cli", "register_system_commands"),
    "register_colony_commands": ("meowcat.cli", "register_colony_commands"),
    "is_debug":               ("meowcat.cli", "is_debug"),
    "MeowTui":                ("meowcat.cli.app", "MeowTui"),
    # — defaults —
    "create_cat":   ("meowcat.defaults", "create_cat"),
    "_UNSET":       ("meowcat.defaults", "_UNSET"),
    "NoopAmygdala":   ("meowcat.defaults", "NoopAmygdala"),
    "NoopBrainstem":  ("meowcat.defaults", "NoopBrainstem"),
    "NoopFrontal":    ("meowcat.defaults", "NoopFrontal"),
    "NoopHypothalamus": ("meowcat.defaults", "NoopHypothalamus"),
    "NoopCortex":     ("meowcat.defaults", "NoopCortex"),
    "NoopCerebrum":   ("meowcat.defaults", "NoopCerebrum"),
    "NoopCerebellum": ("meowcat.defaults", "NoopCerebellum"),
    "NoopEars":       ("meowcat.defaults", "NoopEars"),
    "NoopEyes":       ("meowcat.defaults", "NoopEyes"),
    "NoopWhiskers":   ("meowcat.defaults", "NoopWhiskers"),
    "NoopMouth":      ("meowcat.defaults", "NoopMouth"),
    "NoopPaws":       ("meowcat.defaults", "NoopPaws"),
    "NoopPurr":       ("meowcat.defaults", "NoopPurr"),
    "NoopTail":       ("meowcat.defaults", "NoopTail"),
    "NoopThalamus":   ("meowcat.defaults", "NoopThalamus"),
    "NoopHippocampus": ("meowcat.defaults", "NoopHippocampus"),
    "NoopAnomalyGrowth":   ("meowcat.defaults", "NoopAnomalyGrowth"),
    "NoopCorrectionGrowth": ("meowcat.defaults", "NoopCorrectionGrowth"),
    "NoopCrystallizer":    ("meowcat.defaults", "NoopCrystallizer"),
    "NoopRoleEmergence":   ("meowcat.defaults", "NoopRoleEmergence"),
    "RENOVATED_ORGAN_MAP":     ("meowcat.defaults", "RENOVATED_ORGAN_MAP"),
    "RenovatedAmygdala":        ("meowcat.defaults", "RenovatedAmygdala"),
    "RenovatedBrainstem":       ("meowcat.defaults", "RenovatedBrainstem"),
    "RenovatedFrontal":         ("meowcat.defaults", "RenovatedFrontal"),
    "RenovatedHypothalamus":    ("meowcat.defaults", "RenovatedHypothalamus"),
    "RenovatedCortex":          ("meowcat.defaults", "RenovatedCortex"),
    "RenovatedCerebrum":        ("meowcat.defaults", "RenovatedCerebrum"),
    "RenovatedCerebellum":      ("meowcat.defaults", "RenovatedCerebellum"),
    "RenovatedEars":            ("meowcat.defaults", "RenovatedEars"),
    "RenovatedEyes":            ("meowcat.defaults", "RenovatedEyes"),
    "RenovatedMouth":           ("meowcat.defaults", "RenovatedMouth"),
    "RenovatedPaws":            ("meowcat.defaults", "RenovatedPaws"),
    "RenovatedPurr":            ("meowcat.defaults", "RenovatedPurr"),
    "RenovatedTail":            ("meowcat.defaults", "RenovatedTail"),
    "RenovatedWhiskers":        ("meowcat.defaults", "RenovatedWhiskers"),
    "RenovatedThalamus":        ("meowcat.defaults", "RenovatedThalamus"),
    "RenovatedHippocampus":     ("meowcat.defaults", "RenovatedHippocampus"),
    "RenovatedAnomalyGrowth":   ("meowcat.defaults", "RenovatedAnomalyGrowth"),
    "RenovatedCorrectionGrowth": ("meowcat.defaults", "RenovatedCorrectionGrowth"),
    "RenovatedCrystallizer":    ("meowcat.defaults", "RenovatedCrystallizer"),
    "RenovatedRoleEmergence":   ("meowcat.defaults", "RenovatedRoleEmergence"),
    "KeywordPreset":  ("meowcat.defaults", "KeywordPreset"),
    "OrganPrompt":   ("meowcat.defaults", "OrganPrompt"),
    "PromptPreset":   ("meowcat.defaults", "PromptPreset"),
    "KW_EN":          ("meowcat.defaults", "KW_EN"),
    "KW_ZH":          ("meowcat.defaults", "KW_ZH"),
    "KW_BILINGUAL":   ("meowcat.defaults", "KW_BILINGUAL"),
    "PROMPT_DEFAULT": ("meowcat.defaults", "PROMPT_DEFAULT"),
    "PROMPT_ZH":      ("meowcat.defaults", "PROMPT_ZH"),
    "KW_PRESETS":     ("meowcat.defaults", "KW_PRESETS"),
    "PROMPT_PRESETS": ("meowcat.defaults", "PROMPT_PRESETS"),
    "BaseStage":             ("meowcat.defaults.stages", "BaseStage"),
    "NoopIngestStage":       ("meowcat.defaults.stages", "NoopIngestStage"),
    "NoopLocateStage":       ("meowcat.defaults.stages", "NoopLocateStage"),
    "NoopRouteStage":        ("meowcat.defaults.stages", "NoopRouteStage"),
    "NoopExecuteStage":      ("meowcat.defaults.stages", "NoopExecuteStage"),
    "NoopPostStage":         ("meowcat.defaults.stages", "NoopPostStage"),
    "NoopCompressStage":     ("meowcat.defaults.stages", "NoopCompressStage"),
    "build_default_pipeline": ("meowcat.defaults.stages", "build_default_pipeline"),
    "InMemoryGraphStore":  ("meowcat.defaults", "InMemoryGraphStore"),
    "InMemoryL6Store":     ("meowcat.defaults", "InMemoryL6Store"),
    "InMemoryVectorStore": ("meowcat.defaults", "InMemoryVectorStore"),
    "InMemorySharedStore": ("meowcat.defaults", "InMemorySharedStore"),
    # — anatomy —
    "ImplementationStyle": ("meowcat.anatomy", "ImplementationStyle"),
    # — organ_roles —
    "ORGAN_ROLES": ("meowcat.organ_roles", "ORGAN_ROLES"),
    # — adapters (v1.2.14) —
    "AgentOrgan":           ("meowcat.adapters", "AgentOrgan"),
    "SkillOrgan":           ("meowcat.adapters", "SkillOrgan"),
    "CerebrumAgent":        ("meowcat.adapters", "CerebrumAgent"),
    "CerebellumAgent":      ("meowcat.adapters", "CerebellumAgent"),
    "ThalamusAgent":        ("meowcat.adapters", "ThalamusAgent"),
    "HippocampusAgent":     ("meowcat.adapters", "HippocampusAgent"),
    "AmygdalaAgent":        ("meowcat.adapters", "AmygdalaAgent"),
    "BrainstemAgent":       ("meowcat.adapters", "BrainstemAgent"),
    "FrontalAgent":         ("meowcat.adapters", "FrontalAgent"),
    "HypothalamusAgent":    ("meowcat.adapters", "HypothalamusAgent"),
    "CortexAgent":          ("meowcat.adapters", "CortexAgent"),
    "EarsAgent":            ("meowcat.adapters", "EarsAgent"),
    "EyesAgent":            ("meowcat.adapters", "EyesAgent"),
    "WhiskersAgent":        ("meowcat.adapters", "WhiskersAgent"),
    "PawsAgent":            ("meowcat.adapters", "PawsAgent"),
    "MouthAgent":           ("meowcat.adapters", "MouthAgent"),
    "PurrAgent":            ("meowcat.adapters", "PurrAgent"),
    "TailAgent":            ("meowcat.adapters", "TailAgent"),
    # — events_payloads (v1.2.18) —
    "LifecycleStartPayload":         ("meowcat.events_payloads", "LifecycleStartPayload"),
    "LifecycleShutdownPayload":      ("meowcat.events_payloads", "LifecycleShutdownPayload"),
    "PerceiveStartPayload":          ("meowcat.events_payloads", "PerceiveStartPayload"),
    "PerceiveEndPayload":            ("meowcat.events_payloads", "PerceiveEndPayload"),
    "NerveSignalPayload":            ("meowcat.events_payloads", "NerveSignalPayload"),
    "LocatePrePayload":              ("meowcat.events_payloads", "LocatePrePayload"),
    "LocatePostPayload":             ("meowcat.events_payloads", "LocatePostPayload"),
    "RouteDecidedPayload":           ("meowcat.events_payloads", "RouteDecidedPayload"),
    "RememberPrePayload":            ("meowcat.events_payloads", "RememberPrePayload"),
    "RememberPostPayload":           ("meowcat.events_payloads", "RememberPostPayload"),
    "CompressPrePayload":            ("meowcat.events_payloads", "CompressPrePayload"),
    "CompressPostPayload":           ("meowcat.events_payloads", "CompressPostPayload"),
    "OrchestrateStartPayload":       ("meowcat.events_payloads", "OrchestrateStartPayload"),
    "OrchestrateEndPayload":         ("meowcat.events_payloads", "OrchestrateEndPayload"),
    "GrowthAnomalyPayload":          ("meowcat.events_payloads", "GrowthAnomalyPayload"),
    "GrowthCorrectionPayload":       ("meowcat.events_payloads", "GrowthCorrectionPayload"),
    "CrystallizePayload":            ("meowcat.events_payloads", "CrystallizePayload"),
    "RoleEmergePayload":             ("meowcat.events_payloads", "RoleEmergePayload"),
    "KittenSpawnedPayload":          ("meowcat.events_payloads", "KittenSpawnedPayload"),
    "KittenExecutingPayload":        ("meowcat.events_payloads", "KittenExecutingPayload"),
    "KittenCompletedPayload":        ("meowcat.events_payloads", "KittenCompletedPayload"),
    "KittenStuckPayload":            ("meowcat.events_payloads", "KittenStuckPayload"),
    "KittenDismissedPayload":        ("meowcat.events_payloads", "KittenDismissedPayload"),
    "KittenMergeAbsorbedPayload":    ("meowcat.events_payloads", "KittenMergeAbsorbedPayload"),
    "SelfSnapshotPayload":           ("meowcat.events_payloads", "SelfSnapshotPayload"),
    "SelfReflectPayload":            ("meowcat.events_payloads", "SelfReflectPayload"),
    "FusionSelfPayload":             ("meowcat.events_payloads", "FusionSelfPayload"),
    "FusionColonyPayload":           ("meowcat.events_payloads", "FusionColonyPayload"),
    "FusionTriggerStartPayload":     ("meowcat.events_payloads", "FusionTriggerStartPayload"),
    "FusionTriggerEndPayload":       ("meowcat.events_payloads", "FusionTriggerEndPayload"),
    "EVENT_PAYLOAD_MAP":             ("meowcat.events_payloads", "EVENT_PAYLOAD_MAP"),
    # — telemetry (v1.2.21) —
    "SignalSpan":             ("meowcat.telemetry", "SignalSpan"),
    "Tracer":                 ("meowcat.telemetry", "Tracer"),
    "Metrics":                ("meowcat.telemetry", "Metrics"),
    "TelemetryEvent":         ("meowcat.events", "TelemetryEvent"),
    "TelemetrySpanPayload":   ("meowcat.events_payloads", "TelemetrySpanPayload"),
    # — model shelf (v1.3.6) —
    "ProviderEntry":    ("meowcat.models_shelf", "ProviderEntry"),
    "BUILTIN_PROVIDERS": ("meowcat.models_shelf", "BUILTIN_PROVIDERS"),
    "ModelShelf":       ("meowcat.models_shelf", "ModelShelf"),
    "FallbackChain":    ("meowcat.models_shelf", "FallbackChain"),
    # — compression (v1.3.6) —
    "CompressionManager": ("meowcat.compression", "CompressionManager"),
    "CompressionConfig":  ("meowcat.compression", "CompressionConfig"),
    # — remember (v1.3.6) —
    "RememberPolicy": ("meowcat.remember", "RememberPolicy"),
    "RememberConfig": ("meowcat.remember", "RememberConfig"),
    # — clarify (v1.3.6) —
    "ClarifyManager": ("meowcat.clarify", "ClarifyManager"),
    "ClarifyConfig":  ("meowcat.clarify", "ClarifyConfig"),
    "ClarifyResult":  ("meowcat.clarify", "ClarifyResult"),
    # — budget (v1.3.6) —
    "BudgetTracker": ("meowcat.budget", "BudgetTracker"),
    "BudgetConfig":  ("meowcat.budget", "BudgetConfig"),
    # — noise (v1.3.6) —
    "NoiseFilter":       ("meowcat.noise", "NoiseFilter"),
    "NoiseFilterConfig": ("meowcat.noise", "NoiseFilterConfig"),
    # — scheduler (v1.3.6) —
    "PeriodicScheduler": ("meowcat.scheduler", "PeriodicScheduler"),
    "PeriodicConfig":    ("meowcat.scheduler", "PeriodicConfig"),
    "PeriodicTask":      ("meowcat.scheduler", "PeriodicTask"),
    # — topic closure (v1.3.6) —
    "TopicClosureDetector": ("meowcat.topic_closure", "TopicClosureDetector"),
    "TopicClosureConfig":   ("meowcat.topic_closure", "TopicClosureConfig"),
    "TopicClosureResult":   ("meowcat.topic_closure", "TopicClosureResult"),
    # — checkpoint (v1.3.6) —
    "CheckpointConfig":    ("meowcat.checkpoint", "CheckpointConfig"),
    "JsonCheckpointStore": ("meowcat.checkpoint", "JsonCheckpointStore"),
    # — focus (v1.3.6) —
    "FocusStore":     ("meowcat.focus", "FocusStore"),
    "JsonFocusStore": ("meowcat.focus", "JsonFocusStore"),
    "FocusState":     ("meowcat.focus", "FocusState"),
    # — plan_reviser (v1.3.6) —
    "PlanReviser":       ("meowcat.plan_reviser", "PlanReviser"),
    "PlanReviserConfig": ("meowcat.plan_reviser", "PlanReviserConfig"),
    "RevisionStrategy":  ("meowcat.plan_reviser", "RevisionStrategy"),
    "RevisionContext":   ("meowcat.plan_reviser", "RevisionContext"),
    "RevisionResult":    ("meowcat.plan_reviser", "RevisionResult"),
    # — task_orchestrator (v1.3.6) —
    "TaskOrchestrator": ("meowcat.task_orchestrator", "TaskOrchestrator"),
    "TaskNode":         ("meowcat.task_orchestrator", "TaskNode"),
    "TaskStatus":       ("meowcat.task_orchestrator", "TaskStatus"),
    "TaskResult":       ("meowcat.task_orchestrator", "TaskResult"),
    "TaskExecutor":     ("meowcat.task_orchestrator", "TaskExecutor"),
}

# — Submodule names (lazy via importlib) —
_SUBMODULES: frozenset[str] = frozenset({"anatomy", "biology", "organ_roles"})
