# Copyright (c) 2026 Axonant
# SPDX-License-Identifier: MIT

"""meowcat lazy import map — name → (module_path, attribute).

Extracted from ``_exports.py`` (v1.3.9) to keep each file ≤500 lines.
Imported and re-exported by ``_exports.py`` for backward compatibility.
"""

from __future__ import annotations

# -- Lazy import map: name → (module_path, attribute) ------------------------
# First access to any name triggers importlib.import_module + getattr,
# then caches result in meowcat.__dict__ so __getattr__ is only called once.
_LAZY_MAP: dict[str, tuple[str, str]] = {
    # — protocols —
    "OrchestratorProtocol": ("meowcat.protocols", "OrchestratorProtocol"),
    "SettingsProtocol": ("meowcat.protocols", "SettingsProtocol"),
    "OrganProtocol": ("meowcat.protocols", "OrganProtocol"),
    "CatProtocol": ("meowcat.protocols", "CatProtocol"),
    "KittenProtocol": ("meowcat.protocols", "KittenProtocol"),
    "BrainStemProtocol": ("meowcat.protocols", "BrainStemProtocol"),
    "HippocampusProtocol": ("meowcat.protocols", "HippocampusProtocol"),
    "ThalamusProtocol": ("meowcat.protocols", "ThalamusProtocol"),
    "LLMBrainProtocol": ("meowcat.protocols", "LLMBrainProtocol"),
    "AdapterProtocol": ("meowcat.protocols", "AdapterProtocol"),
    "AmygdalaProtocol": ("meowcat.protocols", "AmygdalaProtocol"),
    "FrontalCortexProtocol": ("meowcat.protocols", "FrontalCortexProtocol"),
    "HypothalamusProtocol": ("meowcat.protocols", "HypothalamusProtocol"),
    "CortexProtocol": ("meowcat.protocols", "CortexProtocol"),
    "EarsProtocol": ("meowcat.protocols", "EarsProtocol"),
    "EyesProtocol": ("meowcat.protocols", "EyesProtocol"),
    "WhiskersProtocol": ("meowcat.protocols", "WhiskersProtocol"),
    "MouthProtocol": ("meowcat.protocols", "MouthProtocol"),
    "PurrProtocol": ("meowcat.protocols", "PurrProtocol"),
    "TailProtocol": ("meowcat.protocols", "TailProtocol"),
    "AnomalyGrowthProtocol": ("meowcat.protocols", "AnomalyGrowthProtocol"),
    "CorrectionGrowthProtocol": ("meowcat.protocols", "CorrectionGrowthProtocol"),
    "CrystallizerProtocol": ("meowcat.protocols", "CrystallizerProtocol"),
    "RoleEmergenceProtocol": ("meowcat.protocols", "RoleEmergenceProtocol"),
    "SecurityPolicyProtocol": ("meowcat.protocols", "SecurityPolicyProtocol"),
    "PawsProtocol": ("meowcat.protocols", "PawsProtocol"),
    "GraphStorageProtocol": ("meowcat.protocols", "GraphStorageProtocol"),
    "VectorStorageProtocol": ("meowcat.protocols", "VectorStorageProtocol"),
    "SharedStorageProtocol": ("meowcat.protocols", "SharedStorageProtocol"),
    "StageProtocol": ("meowcat.protocols", "StageProtocol"),
    "LLMProviderProtocol": ("meowcat.protocols", "LLMProviderProtocol"),
    "Diagnosable": ("meowcat.protocols", "Diagnosable"),
    # — models —
    "EntityShape": ("meowcat.models", "EntityShape"),
    "ConnectionShape": ("meowcat.models", "ConnectionShape"),
    "EpisodeShape": ("meowcat.models", "EpisodeShape"),
    "FocusShape": ("meowcat.models", "FocusShape"),
    "SubTaskShape": ("meowcat.models", "SubTaskShape"),
    "TaskResultShape": ("meowcat.models", "TaskResultShape"),
    "OrchestratorReportShape": ("meowcat.models", "OrchestratorReportShape"),
    "CandidateShape": ("meowcat.models", "CandidateShape"),
    "LocateResultShape": ("meowcat.models", "LocateResultShape"),
    "MaintenanceReportShape": ("meowcat.models", "MaintenanceReportShape"),
    "StageEvent": ("meowcat.models", "StageEvent"),
    "PipelineContext": ("meowcat.models", "PipelineContext"),
    "LoopEvent": ("meowcat.models", "LoopEvent"),
    "MergeProposalShape": ("meowcat.models", "MergeProposalShape"),
    "KittenCapability": ("meowcat.models", "KittenCapability"),
    "WorkflowShape": ("meowcat.models", "WorkflowShape"),
    "ModelConfig": ("meowcat.models", "ModelConfig"),
    # — v2.0 models —
    "TreeNode": ("meowcat.tree", "TreeNode"),
    # — errors —
    "MeowCatError": ("meowcat.errors", "MeowCatError"),
    "OrganNotMountedError": ("meowcat.errors", "OrganNotMountedError"),
    "LoopFailedError": ("meowcat.errors", "LoopFailedError"),
    "StageTimeoutError": ("meowcat.errors", "StageTimeoutError"),
    "IllegalNeuralPathError": ("meowcat.errors", "IllegalNeuralPathError"),
    "ReflexPathInvalidError": ("meowcat.errors", "ReflexPathInvalidError"),
    "NoReflexMatchedError": ("meowcat.errors", "NoReflexMatchedError"),
    "OrganProtocolMismatchError": ("meowcat.errors", "OrganProtocolMismatchError"),
    "StandaloneCatError": ("meowcat.errors", "StandaloneCatError"),
    "CircuitOpenError": ("meowcat.errors", "CircuitOpenError"),
    "OrganDelegateError": ("meowcat.errors", "OrganDelegateError"),
    # — skeleton / assembly —
    "CatBase": ("meowcat.assembly", "CatBase"),
    "CatHook": ("meowcat.assembly", "CatHook"),
    "assemble_default_cat": ("meowcat.assembly", "assemble_default_cat"),
    "mount_known_organs": ("meowcat.assembly", "mount_known_organs"),
    # — colony —
    "Colony": ("meowcat.colony", "Colony"),
    "ColonyConfig": ("meowcat.colony", "ColonyConfig"),
    "ColonyOwner": ("meowcat.colony", "ColonyOwner"),
    "ColonyRules": ("meowcat.colony", "ColonyRules"),
    "SharedMemoryPool": ("meowcat.colony.memory", "SharedMemoryPool"),
    # — events —
    "EventBus": ("meowcat.events", "EventBus"),
    "ALL_EVENTS": ("meowcat.events", "ALL_EVENTS"),
    "FusionEvent": ("meowcat.events", "FusionEvent"),
    "GrowthEvent": ("meowcat.events", "GrowthEvent"),
    "KittenEvent": ("meowcat.events", "KittenEvent"),
    "Lifecycle": ("meowcat.events", "Lifecycle"),
    "LocateEvent": ("meowcat.events", "LocateEvent"),
    "NerveEvent": ("meowcat.events", "NerveEvent"),
    "OrchestrateEvent": ("meowcat.events", "OrchestrateEvent"),
    "RememberEvent": ("meowcat.events", "RememberEvent"),
    "SelfEvent": ("meowcat.events", "SelfEvent"),
    # — wiring / nervous / reflex / host —
    "OrganHost": ("meowcat.host", "OrganHost"),
    "Nervous": ("meowcat.nervous", "Nervous"),
    "SignalCall": ("meowcat.nervous", "SignalCall"),
    "SignalMiddleware": ("meowcat.nervous", "SignalMiddleware"),
    "CircuitState": ("meowcat.nervous", "CircuitState"),
    "Wiring": ("meowcat.wiring", "Wiring"),
    "WiringSnapshot": ("meowcat.wiring", "WiringSnapshot"),
    "Organ": ("meowcat.wiring", "Organ"),
    "Edge": ("meowcat.wiring", "Edge"),
    "ReflexArc": ("meowcat.reflex", "ReflexArc"),
    "Reflex": ("meowcat.reflex", "Reflex"),
    "ReflexRegistry": ("meowcat.reflex", "ReflexRegistry"),
    "Trigger": ("meowcat.reflex", "Trigger"),
    "BUILTIN_REFLEX_PATHS": ("meowcat.reflex", "BUILTIN_REFLEX_PATHS"),
    # — middleware —
    "SignalLogger": ("meowcat.middleware", "SignalLogger"),
    "RateLimiter": ("meowcat.middleware", "RateLimiter"),
    "TimeoutGuard": ("meowcat.middleware", "TimeoutGuard"),
    "ContextInjector": ("meowcat.middleware", "ContextInjector"),
    # — pluggable / organ_base —
    "Pluggable": ("meowcat.pluggable", "Pluggable"),
    "OrganMixin": ("meowcat.organ_base", "OrganMixin"),
    # — pipeline —
    "Pipeline": ("meowcat.pipeline", "Pipeline"),
    # — perception —
    "PerceptionContext": ("meowcat.perception", "PerceptionContext"),
    "Modality": ("meowcat.perception", "Modality"),
    "infer_modality": ("meowcat.perception", "infer_modality"),
    # — diagnosis / injection —
    "Stethoscope": ("meowcat.diagnose", "Stethoscope"),
    "render_wiring": ("meowcat.diagnose", "render_wiring"),
    "Needle": ("meowcat.inject", "Needle"),
    "NeedleDisabledError": ("meowcat.inject", "NeedleDisabledError"),
    # — path / chain / loops —
    "Path": ("meowcat.path", "Path"),
    "PathRegistry": ("meowcat.path", "PathRegistry"),
    "BUILTIN_PATHS": ("meowcat.path", "BUILTIN_PATHS"),
    "register_builtin_paths": ("meowcat.path", "register_builtin_paths"),
    "Chain": ("meowcat.chain", "Chain"),
    "ChainRegistry": ("meowcat.chain", "ChainRegistry"),
    "BUILTIN_CHAINS": ("meowcat.chain", "BUILTIN_CHAINS"),
    "register_builtin_chains": ("meowcat.chain", "register_builtin_chains"),
    "MEMORY_SEARCH_CHAIN": ("meowcat.chain", "MEMORY_SEARCH_CHAIN"),
    "FULL_REASONING_CHAIN": ("meowcat.chain", "FULL_REASONING_CHAIN"),
    "TOOL_EXEC_CHAIN": ("meowcat.chain", "TOOL_EXEC_CHAIN"),
    "MAINTENANCE_CHAIN": ("meowcat.chain", "MAINTENANCE_CHAIN"),
    "DIAGNOSTIC_CHAIN": ("meowcat.chain", "DIAGNOSTIC_CHAIN"),
    "WORKFLOW_CHAIN": ("meowcat.chain", "WORKFLOW_CHAIN"),
    "Loop": ("meowcat.loops", "Loop"),
    "LoopRegistry": ("meowcat.loops", "LoopRegistry"),
    "BUILTIN_LOOPS": ("meowcat.loops", "BUILTIN_LOOPS"),
    "register_default_loops": ("meowcat.loops", "register_default_loops"),
    "CONVERSATION_LOOP": ("meowcat.loops", "CONVERSATION_LOOP"),
    "TOOL_EXECUTION_LOOP": ("meowcat.loops", "TOOL_EXECUTION_LOOP"),
    "DANGER_RESPONSE_LOOP": ("meowcat.loops", "DANGER_RESPONSE_LOOP"),
    "MAINTENANCE_LOOP": ("meowcat.loops", "MAINTENANCE_LOOP"),
    "DIAGNOSTIC_LOOP": ("meowcat.loops", "DIAGNOSTIC_LOOP"),
    "LoopSequence": ("meowcat.loops", "LoopSequence"),
    "LoopSequenceRegistry": ("meowcat.loops", "LoopSequenceRegistry"),
    "DAILY_MAINTENANCE_SEQ": ("meowcat.loops", "DAILY_MAINTENANCE_SEQ"),
    # — tools (pure abstractions) —
    "Tool": ("meowcat.tools", "Tool"),
    "ToolSpec": ("meowcat.tools", "ToolSpec"),
    "ToolRegistry": ("meowcat.tools", "ToolRegistry"),
    "RiskLevel": ("meowcat.tools", "RiskLevel"),
    "Skill": ("meowcat.tools", "Skill"),
    "SkillSpec": ("meowcat.tools", "SkillSpec"),
    "SkillRegistry": ("meowcat.tools", "SkillRegistry"),
    "PawsEngine": ("meowcat.tools", "PawsEngine"),
    "KeywordToolMatcher": ("meowcat.tools", "KeywordToolMatcher"),
    # — plus (concrete implementations) —
    "ChromaStore": ("meowcat.plus", "ChromaStore"),
    "SkillLoader": ("meowcat.plus", "SkillLoader"),
    "Crystallizer": ("meowcat.plus", "Crystallizer"),
    "DefaultDetector": ("meowcat.plus", "DefaultDetector"),
    # — storage —
    "SharedStore": ("meowcat.storage", "SharedStore"),
    "SqliteGraphStore": ("meowcat.storage", "SqliteGraphStore"),
    "JsonlL6Store": ("meowcat.storage", "JsonlL6Store"),
    "JsonlEpisodeStore": ("meowcat.storage", "JsonlEpisodeStore"),
    "VectorStore": ("meowcat.storage", "VectorStore"),
    # — biology —
    "CollectiveGrowth": ("meowcat.biology", "CollectiveGrowth"),
    "CollectiveEmergence": ("meowcat.biology.growth", "CollectiveEmergence"),
    "OrganSpec": ("meowcat.biology", "OrganSpec"),
    "ANOMALY_GROWTH": ("meowcat.biology", "ANOMALY_GROWTH"),
    "CORRECTION_GROWTH": ("meowcat.biology", "CORRECTION_GROWTH"),
    "CRYSTALLIZER": ("meowcat.biology", "CRYSTALLIZER"),
    "ROLE_EMERGENCE": ("meowcat.biology", "ROLE_EMERGENCE"),
    "ScribblePad": ("meowcat.biology.scribble_pad", "ScribblePad"),
    "DefaultScribbleFilter": ("meowcat.biology.scribble_pad", "DefaultScribbleFilter"),
    "DefaultScribbleLogger": ("meowcat.biology.scribble_pad", "DefaultScribbleLogger"),
    "DefaultScribblePersister": ("meowcat.biology.scribble_pad", "DefaultScribblePersister"),
    "PinealGland": ("meowcat.biology.pineal_gland", "PinealGland"),
    "Insight": ("meowcat.biology.pineal_gland", "Insight"),
    "DefaultMerger": ("meowcat.biology.pineal_gland", "DefaultMerger"),
    "DefaultContradiction": ("meowcat.biology.pineal_gland", "DefaultContradiction"),
    "DefaultInsightFilter": ("meowcat.biology.pineal_gland", "DefaultInsightFilter"),
    "Cortex": ("meowcat.biology.cortex", "Cortex"),
    "DefaultRuleExtractor": ("meowcat.biology.cortex", "DefaultRuleExtractor"),
    "BlindSpotDetector": ("meowcat.biology.active_growth", "BlindSpotDetector"),
    "ToolFailureLearner": ("meowcat.biology.active_growth", "ToolFailureLearner"),
    "HotPathObserver": ("meowcat.biology.active_growth", "HotPathObserver"),
    "ActiveGrowthPack": ("meowcat.biology.active_growth_pack", "ActiveGrowthPack"),
    "CatSelf": ("meowcat.biology.cat_self", "CatSelf"),
    "SelfSnapshot": ("meowcat.biology.cat_self", "SelfSnapshot"),
    "ReflectionLoop": ("meowcat.biology.cat_self_loops", "ReflectionLoop"),
    # — log —
    "MeowLog": ("meowcat.log", "MeowLog"),
    # — coordination —
    "AsyncApprovalGate": ("meowcat.coordination", "AsyncApprovalGate"),
    "ApprovalRequest": ("meowcat.coordination", "ApprovalRequest"),
    "ApprovalStatus": ("meowcat.coordination", "ApprovalStatus"),
    # — worker —
    "BaseWorker": ("meowcat.worker", "BaseWorker"),
    "CheckpointStore": ("meowcat.worker", "WorkerCheckpointStore"),
    "InMemoryCheckpointStore": ("meowcat.worker", "InMemoryCheckpointStore"),
    "WorkerState": ("meowcat.worker", "WorkerState"),
    "WorkerStatus": ("meowcat.worker", "WorkerStatus"),
    "WorkerScheduler": ("meowcat.worker.scheduler", "WorkerScheduler"),
    # — utils —
    "get_shared_client": ("meowcat.utils", "get_shared_client"),
    "close_shared_client": ("meowcat.utils", "close_shared_client"),
    # — gateway —
    "Gateway": ("meowcat.gateway", "Gateway"),
    "SignalContext": ("meowcat.gateway.protocol", "SignalContext"),
    "IoAdapterProtocol": ("meowcat.gateway.protocol", "IoAdapterProtocol"),
    "FrontDeskProtocol": ("meowcat.gateway.protocol", "FrontDeskProtocol"),
    "GatewayProtocol": ("meowcat.gateway.protocol", "GatewayProtocol"),
    "DefaultFrontDesk": ("meowcat.gateway.front_desk", "DefaultFrontDesk"),
    # — defaults —
    "create_cat": ("meowcat.defaults", "create_cat"),
    "_UNSET": ("meowcat.defaults", "_UNSET"),
    "DefaultAmygdala": ("meowcat.defaults", "DefaultAmygdala"),
    "DefaultBrainstem": ("meowcat.defaults", "DefaultBrainstem"),
    "DefaultFrontal": ("meowcat.defaults", "DefaultFrontal"),
    "DefaultHypothalamus": ("meowcat.defaults", "DefaultHypothalamus"),
    "DefaultCortex": ("meowcat.defaults", "DefaultCortex"),
    "DefaultCerebrum": ("meowcat.defaults", "DefaultCerebrum"),
    "DefaultCerebellum": ("meowcat.defaults", "DefaultCerebellum"),
    "DefaultEars": ("meowcat.defaults", "DefaultEars"),
    "DefaultEyes": ("meowcat.defaults", "DefaultEyes"),
    "DefaultWhiskers": ("meowcat.defaults", "DefaultWhiskers"),
    "DefaultMouth": ("meowcat.defaults", "DefaultMouth"),
    "DefaultPaws": ("meowcat.defaults", "DefaultPaws"),
    "DefaultPurr": ("meowcat.defaults", "DefaultPurr"),
    "DefaultTail": ("meowcat.defaults", "DefaultTail"),
    "DefaultThalamus": ("meowcat.defaults", "DefaultThalamus"),
    "DefaultHippocampus": ("meowcat.defaults", "DefaultHippocampus"),
    "DefaultAnomalyGrowth": ("meowcat.defaults", "DefaultAnomalyGrowth"),
    "DefaultCorrectionGrowth": ("meowcat.defaults", "DefaultCorrectionGrowth"),
    "DefaultCrystallizer": ("meowcat.defaults", "DefaultCrystallizer"),
    "DefaultRoleEmergence": ("meowcat.defaults", "DefaultRoleEmergence"),
    "KeywordPreset": ("meowcat.defaults", "KeywordPreset"),
    "OrganPrompt": ("meowcat.defaults", "OrganPrompt"),
    "PromptPreset": ("meowcat.defaults", "PromptPreset"),
    "KW_EN": ("meowcat.defaults", "KW_EN"),
    "KW_ZH": ("meowcat.defaults", "KW_ZH"),
    "KW_BILINGUAL": ("meowcat.defaults", "KW_BILINGUAL"),
    "PROMPT_DEFAULT": ("meowcat.defaults", "PROMPT_DEFAULT"),
    "PROMPT_ZH": ("meowcat.defaults", "PROMPT_ZH"),
    "KW_PRESETS": ("meowcat.defaults.presets", "KW_PRESETS"),
    "PROMPT_PRESETS": ("meowcat.defaults.presets", "PROMPT_PRESETS"),
    "BaseStage": ("meowcat.defaults.stages", "BaseStage"),
    "DefaultIngestStage": ("meowcat.defaults.stages", "DefaultIngestStage"),
    "DefaultLocateStage": ("meowcat.defaults.stages", "DefaultLocateStage"),
    "DefaultRouteStage": ("meowcat.defaults.stages", "DefaultRouteStage"),
    "DefaultExecuteStage": ("meowcat.defaults.stages", "DefaultExecuteStage"),
    "DefaultPostStage": ("meowcat.defaults.stages", "DefaultPostStage"),
    "DefaultCompressStage": ("meowcat.defaults.stages", "DefaultCompressStage"),
    "build_default_pipeline": ("meowcat.defaults.stages", "build_default_pipeline"),
    "InMemoryGraphStore": ("meowcat.defaults", "InMemoryGraphStore"),
    "InMemoryL6Store": ("meowcat.defaults", "InMemoryL6Store"),
    "InMemoryVectorStore": ("meowcat.defaults", "InMemoryVectorStore"),
    "InMemorySharedStore": ("meowcat.defaults", "InMemorySharedStore"),
    # — anatomy —
    "ImplementationStyle": ("meowcat.anatomy", "ImplementationStyle"),
    # — organ_roles —
    "ORGAN_ROLES": ("meowcat.organ_roles", "ORGAN_ROLES"),
    # — adapters (v1.2.14) —
    "AgentOrgan": ("meowcat.adapters", "AgentOrgan"),
    "CerebrumAgent": ("meowcat.adapters", "CerebrumAgent"),
    "CerebellumAgent": ("meowcat.adapters", "CerebellumAgent"),
    "ThalamusAgent": ("meowcat.adapters", "ThalamusAgent"),
    "HippocampusAgent": ("meowcat.adapters", "HippocampusAgent"),
    "AmygdalaAgent": ("meowcat.adapters", "AmygdalaAgent"),
    "BrainstemAgent": ("meowcat.adapters", "BrainstemAgent"),
    "FrontalAgent": ("meowcat.adapters", "FrontalAgent"),
    "HypothalamusAgent": ("meowcat.adapters", "HypothalamusAgent"),
    "CortexAgent": ("meowcat.adapters", "CortexAgent"),
    "EarsAgent": ("meowcat.adapters", "EarsAgent"),
    "EyesAgent": ("meowcat.adapters", "EyesAgent"),
    "WhiskersAgent": ("meowcat.adapters", "WhiskersAgent"),
    "PawsAgent": ("meowcat.adapters", "PawsAgent"),
    "MouthAgent": ("meowcat.adapters", "MouthAgent"),
    "PurrAgent": ("meowcat.adapters", "PurrAgent"),
    "TailAgent": ("meowcat.adapters", "TailAgent"),
    # — events_payloads (v1.2.18) —
    "LifecycleStartPayload": ("meowcat.events_payloads", "LifecycleStartPayload"),
    "LifecycleShutdownPayload": ("meowcat.events_payloads", "LifecycleShutdownPayload"),
    "PerceiveStartPayload": ("meowcat.events_payloads", "PerceiveStartPayload"),
    "PerceiveEndPayload": ("meowcat.events_payloads", "PerceiveEndPayload"),
    "NerveSignalPayload": ("meowcat.events_payloads", "NerveSignalPayload"),
    "LocatePrePayload": ("meowcat.events_payloads", "LocatePrePayload"),
    "LocatePostPayload": ("meowcat.events_payloads", "LocatePostPayload"),
    "RouteDecidedPayload": ("meowcat.events_payloads", "RouteDecidedPayload"),
    "RememberPrePayload": ("meowcat.events_payloads", "RememberPrePayload"),
    "RememberPostPayload": ("meowcat.events_payloads", "RememberPostPayload"),
    "CompressPrePayload": ("meowcat.events_payloads", "CompressPrePayload"),
    "CompressPostPayload": ("meowcat.events_payloads", "CompressPostPayload"),
    "OrchestrateStartPayload": ("meowcat.events_payloads", "OrchestrateStartPayload"),
    "OrchestrateEndPayload": ("meowcat.events_payloads", "OrchestrateEndPayload"),
    "GrowthAnomalyPayload": ("meowcat.events_payloads", "GrowthAnomalyPayload"),
    "GrowthCorrectionPayload": ("meowcat.events_payloads", "GrowthCorrectionPayload"),
    "CrystallizePayload": ("meowcat.events_payloads", "CrystallizePayload"),
    "RoleEmergePayload": ("meowcat.events_payloads", "RoleEmergePayload"),
    "KittenSpawnedPayload": ("meowcat.events_payloads", "KittenSpawnedPayload"),
    "KittenExecutingPayload": ("meowcat.events_payloads", "KittenExecutingPayload"),
    "KittenCompletedPayload": ("meowcat.events_payloads", "KittenCompletedPayload"),
    "KittenStuckPayload": ("meowcat.events_payloads", "KittenStuckPayload"),
    "KittenDismissedPayload": ("meowcat.events_payloads", "KittenDismissedPayload"),
    "KittenMergeAbsorbedPayload": ("meowcat.events_payloads", "KittenMergeAbsorbedPayload"),
    "SelfSnapshotPayload": ("meowcat.events_payloads", "SelfSnapshotPayload"),
    "SelfReflectPayload": ("meowcat.events_payloads", "SelfReflectPayload"),
    "FusionSelfPayload": ("meowcat.events_payloads", "FusionSelfPayload"),
    "FusionColonyPayload": ("meowcat.events_payloads", "FusionColonyPayload"),
    "FusionTriggerStartPayload": ("meowcat.events_payloads", "FusionTriggerStartPayload"),
    "FusionTriggerEndPayload": ("meowcat.events_payloads", "FusionTriggerEndPayload"),
    "EVENT_PAYLOAD_MAP": ("meowcat.events_payloads", "EVENT_PAYLOAD_MAP"),
    # — telemetry (v1.2.21) —
    "SignalSpan": ("meowcat.telemetry", "SignalSpan"),
    "Tracer": ("meowcat.telemetry", "Tracer"),
    "Metrics": ("meowcat.telemetry", "Metrics"),
    "TelemetryEvent": ("meowcat.events", "TelemetryEvent"),
    "TelemetrySpanPayload": ("meowcat.events_payloads", "TelemetrySpanPayload"),
    # — model shelf (v1.3.6) —
    "ProviderEntry": ("meowcat.models_shelf", "ProviderEntry"),
    "BUILTIN_PROVIDERS": ("meowcat.models_shelf", "BUILTIN_PROVIDERS"),
    "ModelShelf": ("meowcat.models_shelf", "ModelShelf"),
    "FallbackChain": ("meowcat.models_shelf", "FallbackChain"),
    # — compression (v1.3.6) —
    "CompressionManager": ("meowcat.compression", "CompressionManager"),
    "CompressionConfig": ("meowcat.compression", "CompressionConfig"),
    # — remember (v1.3.6) —
    "RememberPolicy": ("meowcat.remember", "RememberPolicy"),
    "RememberConfig": ("meowcat.remember", "RememberConfig"),
    # — clarify (v1.3.6) —
    "ClarifyManager": ("meowcat.clarify", "ClarifyManager"),
    "ClarifyConfig": ("meowcat.clarify", "ClarifyConfig"),
    "ClarifyResult": ("meowcat.clarify", "ClarifyResult"),
    # — budget (v1.3.6) —
    "BudgetTracker": ("meowcat.budget", "BudgetTracker"),
    "BudgetConfig": ("meowcat.budget", "BudgetConfig"),
    # — noise (v1.3.6) —
    "NoiseFilter": ("meowcat.noise", "NoiseFilter"),
    "NoiseFilterConfig": ("meowcat.noise", "NoiseFilterConfig"),
    # — scheduler (v1.3.6) —
    "PeriodicScheduler": ("meowcat.scheduler", "PeriodicScheduler"),
    "PeriodicConfig": ("meowcat.scheduler", "PeriodicConfig"),
    "PeriodicTask": ("meowcat.scheduler", "PeriodicTask"),
    # — topic closure (v1.3.6) —
    "TopicClosureDetector": ("meowcat.topic_closure", "TopicClosureDetector"),
    "TopicClosureConfig": ("meowcat.topic_closure", "TopicClosureConfig"),
    "TopicClosureResult": ("meowcat.topic_closure", "TopicClosureResult"),
    # — checkpoint (v1.3.6) —
    "CheckpointConfig": ("meowcat.checkpoint", "CheckpointConfig"),
    "JsonCheckpointStore": ("meowcat.checkpoint", "JsonCheckpointStore"),
    # — focus (v1.3.6) —
    "FocusStore": ("meowcat.focus", "FocusStore"),
    "JsonFocusStore": ("meowcat.focus", "JsonFocusStore"),
    "FocusState": ("meowcat.focus", "FocusState"),
    # — plan_reviser (v1.3.6) —
    "PlanReviser": ("meowcat.plan_reviser", "PlanReviser"),
    "PlanReviserConfig": ("meowcat.plan_reviser", "PlanReviserConfig"),
    "RevisionStrategy": ("meowcat.plan_reviser", "RevisionStrategy"),
    "RevisionContext": ("meowcat.plan_reviser", "RevisionContext"),
    "RevisionResult": ("meowcat.plan_reviser", "RevisionResult"),
    # — task_orchestrator (v1.3.6) —
    "TaskOrchestrator": ("meowcat.task_orchestrator", "TaskOrchestrator"),
    "TaskNode": ("meowcat.task_orchestrator", "TaskNode"),
    "TaskStatus": ("meowcat.task_orchestrator", "TaskStatus"),
    "TaskResult": ("meowcat.task_orchestrator", "TaskResult"),
    "TaskExecutor": ("meowcat.task_orchestrator", "TaskExecutor"),
    # — v2.1.0 RuleSet —
    "Rule": ("meowcat.ruleset", "Rule"),
    "RuleSet": ("meowcat.ruleset", "RuleSet"),
    # — v2.2.0 TaskPad + tools —
    "TaskPad": ("meowcat.biology.task_pad", "TaskPad"),
    "TaskItem": ("meowcat.biology.task_pad", "TaskItem"),
    "TaskPadStatus": ("meowcat.biology.task_pad", "TaskPadStatus"),
    "ToolCall": ("meowcat.tools.tool_call", "ToolCall"),
    "DoTaskResult": ("meowcat.tools.tool_call", "DoTaskResult"),
    "XmlToolCallParser": ("meowcat.tools.tool_call", "XmlToolCallParser"),
}
